language: php

php:
  - 7.1
  - 7.2
  - nightly

env:
- LARAVEL_VERSION="5.4.*"
- LARAVEL_VERSION="5.5.*"
- LARAVEL_VERSION="5.6.*"

install:
  - rm composer.lock
  - composer require illuminate/database:${LARAVEL_VERSION}

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - php vendor/bin/codacycoverage clover clover.xml

cache:
  directories:
    - $HOME/.composer/cache/files

notifications:
  webhooks: https://ci-notification.limenet.xyz/dev/webhook
